import type OpenAI from "openai";
import { ToolInvocationPolicyModel } from "../../../models";

/**
 * This method will evaluate whether, based on the tool invocation policies assigned to the specified agent,
 * if the tool call is allowed or blocked.
 *
 * If this method returns non-null it is because the tool call was blocked and we are returning a refusal message
 * (in the format of an assistant message with a refusal)
 */
export const evaluatePolicies = async (
  { tool_calls: toolCalls }: OpenAI.Chat.Completions.ChatCompletionMessage,
  agentId: string,
): Promise<null | OpenAI.Chat.Completions.ChatCompletion.Choice> => {
  for (const toolCall of toolCalls || []) {
    let toolCallName = "";
    let toolCallArgs = "";

    if (toolCall.type === "function") {
      toolCallName = toolCall.function.name;
      toolCallArgs = toolCall.function.arguments;
    } else {
      toolCallName = toolCall.custom.name;
      toolCallArgs = toolCall.custom.input;
    }

    /**
     * According to the OpenAI TS SDK types.. toolCall.function.arguments mentions:
     *
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does
     * not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate
     * the arguments in your code before calling your function.
     *
     * So it is possible that the "JSON" here is malformed because the model hallucinated parameters and we
     * may need to explicitly handle this case in the future...
     */
    const toolInput = JSON.parse(toolCallArgs);

    const { isAllowed } = await ToolInvocationPolicyModel.evaluateForAgent(
      agentId,
      toolCallName,
      toolInput,
    );

    if (!isAllowed) {
      return {
        finish_reason: "stop",
        index: 0,
        logprobs: null,
        message: {
          role: "assistant",
          refusal: `I tried to invoke the ${toolCallName} tool with the following arguments: ${JSON.stringify(toolInput)}. However, I was denied by a tool invocation policy.`,
          content: null,
        },
      };
    }
  }

  return null;
};
